config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  resources :posts do
    resources :comments, except: :show
  end
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true

  has_many :post_category_ships, dependent: :restrict_with_exception
  has_many :posts, through: :post_category_ships
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  has_many :comments
  has_many :post_category_ships
  has_many :categories, through: :post_category_ships
end

app/models/post_category_ship.rb
class PostCategoryShip < ApplicationRecord
  belongs_to :post
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(params_comment)
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit

  end

  def update
    if @comment.update(params_comment)
      redirect_to post_comments_path(@post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy
    redirect_to post_comments_path(@post)
  end

  private

  def set_post
    @post = Post.find params[:post_id]
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def params_comment
    params.require(:comment).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.includes(:categories).all
  end

  def new
    @post = Post.new
  end

  def create
    #debugger
    #post = Post.new(params[:post])
    #post = Post.new(params[:post].permit(:title, :content))
    #if post.save
    #@post = Post.new(params[:post].permit(:title, :content))
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  #def show @post = Post.find(params[:id]) end
  def show
  end

  #def edit @post = Post.find(params[:id]) end
  def edit
  end

  def update
    #@post = Post.find(params[:id])
    #if @post.update(params.require(:post).permit(:title, :content))
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    #@post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, category_ids: [])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index;  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_with model: category, url: path, data: { turbo: false } do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>category id: <%= @category.id %></h1>
<%= render partial: 'form', locals: { category: @category, path: category_path(@category) } %>

app/views/categories/index.html.erb
<h1>Category</h1>
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= category.name %>
      <%= link_to :edit, edit_category_path(category) %>
      <%= button_to :delete, category_path(category), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New category</h1>
<%= render partial: 'form', locals: { category: @category, path: categories_path } %>

app/views/comments/_form.html.erb
<%= form_with model: comment, url: url do |form| %>
  <% if comment.errors.any? %>
    <ul>
      <% comment.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: 'form-control' %>
  </div>
  <%= form.submit :submit, class: 'btn btn-danger' %>
<% end %>

app/views/comments/edit.html.erb
<h1>Title: <%= @post.title %>, Comment: <%= @comment.content %></h1>
<%= render partial: 'form', locals: { comment: @comment, url: post_comment_path(@post, @comment) } %>
<%= link_to 'Post List', posts_path, class: 'btn btn-primary' %>

app/views/comments/index.html.erb
<h1>Title <%= @post.title %></h1>
<h2>Comments</h2>
<ul>
  <% @comments.each do |comment| %>
    <li>
      <%= comment.content %>(<%= comment.created_at %>)
      <%= link_to :edit, edit_post_comment_path(@post, comment), class: 'btn btn-info' %>
      <%= button_to :delete, post_comment_path(@post, comment), method: :delete, class: 'btn btn-danger' %>
    </li>
  <% end %>
</ul>

<%= link_to 'Post List', posts_path, class: 'btn btn-primary' %>

app/views/comments/new.html.erb
<h1>Title: <%= @post.title %></h1>
<%= render partial: 'form', locals: { comment: @comment, url: post_comments_path(@post) } %>
<%= link_to 'Post List', posts_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
  <% if post.errors.any? %>
    <ul>
      <% post.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  <% end %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_field :content, class: 'form-control' %>
  </div>
  <div>
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name %>
  </div>
  <%= form.submit :submit, class: 'btn btn-danger' %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post id: <%= @post.id %></h1>

<%= render partial: 'form', locals: { post: @post } %>

<%= link_to 'Index', posts_path, class: 'btn btn-primary' %>

app/views/posts/index.html.erb
<br><br>
<h1>Post List</h1>
<style>
    h1, p {
        text-align: center;
        margin: auto;
    }
    table {
        margin-left: auto;
        margin-right: auto;
    }
  #postlist {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 55%;
    }

  #postlist td, #postlist th {
        border: 1px solid #ddd;
        padding: 8px;
        text-align: center;
    }

  #postlist tr:nth-child(even){background-color: #f2f2f2;}

  #postlist tr:hover {background-color: #ddd;}

  #postlist thead {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: left;
        background-color: #326fa8;
        color: white;
    }
</style>


<!--<table class="table table-striped table-hover">-->

  <table id="postlist">
  <thead>
    <td>Title</td>
    <td>Content</td>
    <td>Action</td>
  </thead>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.content %></td>
      <td><%= post.categories.pluck(:name).join(',') %></td>
      <td>
        <%= link_to 'Show', post_path(post), class: 'btn btn-success'%>
        <%= link_to 'Edit', edit_post_path(post), class: 'btn  btn-info'%>
        <%= button_to 'Delete', post_path(post), method: :delete, class: 'btn btn-danger'%>
        <%= link_to 'Comments', post_comments_path(post), class: 'btn btn-dark' %>
        <%= link_to 'New Comment', new_post_comment_path(post), class: 'btn btn-light' %>
      </td>
    </tr>
  <% end %>
</table>

<p>
<%= link_to 'New', new_post_path, class: 'btn btn-primary' %>
</p>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render partial: 'form', locals: { post: @post } %>

<%= link_to 'Index', posts_path, class: 'btn btn-primary' %>

app/views/posts/newpostcss.html.erb
<div class="form">
  <div class="title">New Post</div>
  <div class="input-container ic1">
    <input id="title" class="input" type="text" placeholder=" " />
    <div class="cut"></div>
    <label for="Title" class="placeholder">First name</label>
  </div>
  <div class="input-container ic2">
    <input id="content" class="input" type="text" placeholder=" " />
    <div class="cut"></div>
    <label for="Content" class="placeholder">Last name</label>
  </div>
  <button type="text" class="submit">submit</button>
</div>
<style>
    body {
        align-items: center;
        background-color: #000;
        display: flex;
        justify-content: center;
        height: 100vh;
    }

    .form {
        background-color: #15172b;
        border-radius: 20px;
        box-sizing: border-box;
        height: 500px;
        padding: 20px;
        width: 320px;
    }

    .title {
        color: #eee;
        font-family: sans-serif;
        font-size: 36px;
        font-weight: 600;
        margin-top: 30px;
    }

    /*.subtitle {
        color: #eee;
        font-family: sans-serif;
        font-size: 16px;
        font-weight: 600;
        margin-top: 10px;
    }*/

    .input-container {
        height: 50px;
        position: relative;
        width: 100%;
    }

    .ic1 {
        margin-top: 40px;
    }

    .ic2 {
        margin-top: 30px;
    }

    .input {
        background-color: #303245;
        border-radius: 12px;
        border: 0;
        box-sizing: border-box;
        color: #eee;
        font-size: 18px;
        height: 100%;
        outline: 0;
        padding: 4px 20px 0;
        width: 100%;
    }

    .cut {
        background-color: #15172b;
        border-radius: 10px;
        height: 20px;
        left: 20px;
        position: absolute;
        top: -20px;
        transform: translateY(0);
        transition: transform 200ms;
        width: 76px;
    }

    .cut-short {
        width: 50px;
    }

    .input:focus ~ .cut,
    .input:not(:placeholder-shown) ~ .cut {
        transform: translateY(8px);
    }

    .placeholder {
        color: #65657b;
        font-family: sans-serif;
        left: 20px;
        line-height: 14px;
        pointer-events: none;
        position: absolute;
        transform-origin: 0 50%;
        transition: transform 200ms, color 200ms;
        top: 20px;
    }

    .input:focus ~ .placeholder,
    .input:not(:placeholder-shown) ~ .placeholder {
        transform: translateY(-30px) translateX(10px) scale(0.75);
    }

    .input:not(:placeholder-shown) ~ .placeholder {
        color: #808097;
    }

    .input:focus ~ .placeholder {
        color: #dc2f55;
    }

    .submit {
        background-color: #08d;
        border-radius: 12px;
        border: 0;
        box-sizing: border-box;
        color: #eee;
        cursor: pointer;
        font-size: 18px;
        height: 50px;
        margin-top: 38px;
    // outline: 0;
        text-align: center;
        width: 100%;
    }

    .submit:active {
        background-color: #06b;
    }
</style>

      <%= render partial: 'form', locals: { post: @post } %>

<%= link_to 'Index', posts_path %>

app/views/posts/show.html.erb
<h1>show post id: <%= @post.id %></h1>
<ul>
  <li><%= @post.title %></li>
  <li><%= @post.content %></li>
</ul>

<%= link_to 'Index', posts_path %>

app/views/posts/testcss.html.erb
<div class="form">
  <div class="title">New Post</div>
  <div class="input-container ic1">
    <input id="title" class="input" type="text" placeholder=" " />
    <div class="cut"></div>
    <label for="Title" class="placeholder">First name</label>
  </div>
  <div class="input-container ic2">
    <input id="content" class="input" type="text" placeholder=" " />
    <div class="cut"></div>
    <label for="Content" class="placeholder">Last name</label>
  </div>
  <button type="text" class="submit">submit</button>
</div>
<style>
    body {
        align-items: center;
        background-color: #000;
        display: flex;
        justify-content: center;
        height: 100vh;
    }

    .form {
        background-color: #15172b;
        border-radius: 20px;
        box-sizing: border-box;
        height: 500px;
        padding: 20px;
        width: 320px;
    }

    .title {
        color: #eee;
        font-family: sans-serif;
        font-size: 36px;
        font-weight: 600;
        margin-top: 30px;
    }

    /*.subtitle {
        color: #eee;
        font-family: sans-serif;
        font-size: 16px;
        font-weight: 600;
        margin-top: 10px;
    }*/

    .input-container {
        height: 50px;
        position: relative;
        width: 100%;
    }

    .ic1 {
        margin-top: 40px;
    }

    .ic2 {
        margin-top: 30px;
    }

    .input {
        background-color: #303245;
        border-radius: 12px;
        border: 0;
        box-sizing: border-box;
        color: #eee;
        font-size: 18px;
        height: 100%;
        outline: 0;
        padding: 4px 20px 0;
        width: 100%;
    }

    .cut {
        background-color: #15172b;
        border-radius: 10px;
        height: 20px;
        left: 20px;
        position: absolute;
        top: -20px;
        transform: translateY(0);
        transition: transform 200ms;
        width: 76px;
    }

    .cut-short {
        width: 50px;
    }

    .input:focus ~ .cut,
    .input:not(:placeholder-shown) ~ .cut {
        transform: translateY(8px);
    }

    .placeholder {
        color: #65657b;
        font-family: sans-serif;
        left: 20px;
        line-height: 14px;
        pointer-events: none;
        position: absolute;
        transform-origin: 0 50%;
        transition: transform 200ms, color 200ms;
        top: 20px;
    }

    .input:focus ~ .placeholder,
    .input:not(:placeholder-shown) ~ .placeholder {
        transform: translateY(-30px) translateX(10px) scale(0.75);
    }

    .input:not(:placeholder-shown) ~ .placeholder {
        color: #808097;
    }

    .input:focus ~ .placeholder {
        color: #dc2f55;
    }

    .submit {
        background-color: #08d;
        border-radius: 12px;
        border: 0;
        box-sizing: border-box;
        color: #eee;
        cursor: pointer;
        font-size: 18px;
        height: 50px;
        margin-top: 38px;
    // outline: 0;
        text-align: center;
        width: 100%;
    }

    .submit:active {
        background-color: #06b;
    }
</style>

      <%= render partial: 'form', locals: { post: @post } %>

<%= link_to 'Index', posts_path %>

app/views/welcome/index.html.erb
<h1>Hello World!</h1>
<p>Welcome to my page!</p>
<%= link_to 'Index', posts_path %>